apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Release.Name }}
data:
  releaseName: {{ .Chart.Name }}
  releaseVersion: {{ .Chart.Version }}
  release: {{ .Chart.Name }}:{{ .Chart.Version }}
  COLOR: {{ .Values.ConfigMap.Color }}
  HAIR: {{ .Values.ConfigMap.Hair }}
  LEGS: "{{ .Values.ConfigMap.Legs }}"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-{{ .Release.Name }}
spec:
  restartPolicy: {{ .Values.RestartPolicy }}
  containers:
    - name: configmap-container-{{ .Release.Name }}
      image: {{ .Values.DefaultImageName }}
      command: ['/bin/sh', '-c', 'ls {{ .Values.ConfigMap.Volume.MountPath }}']
      volumeMounts:
      - name: {{.Values.ConfigMap.Volume.Name}}-{{ .Release.Name }} 
        mountPath: {{ .Values.ConfigMap.Volume.MountPath }}
  volumes:
    - name: {{ .Values.ConfigMap.Volume.Name }}-{{ .Release.Name }}
      configMap:
        name: configmap-{{ .Release.Name }}
