apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Release.Name }}
stringData:
  version: {{ .Chart.Version }}
  TEST_ENVSECRET: {{ .Values.Secret.TestEnvSecret }}
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-{{ .Release.Name }}
spec:
  restartPolicy: {{ .Values.RestartPolicy }}
  containers:
    - name: secret-container-{{ .Release.Name }}
      image: {{ .Values.DefaultImageName }}
      command: ['/bin/sh', '-c', 'env']
      envFrom:
        - secretRef:
            name: secret-{{ .Release.Name }}
